runtime: custom
api_version: '1.0'
env: flexible

env_variables:
  DB_HOST: 
  DB_NAME: 
  DB_PASSWORD: 
  DB_PORT: '3306'
  DB_TYPE: cloudsql
  DB_USER: root

automatic_scaling:
  min_num_instances: 0
  max_num_instances: 2
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6
  target_concurrent_requests: 100

network:
  instance_tag: default
  name: default
