env: flex
runtime: python
entrypoint: gunicorn -b :$PORT blog.wsgi
runtime_config:
  python_version: 3
#network:
#  instance_ip_mode: internal
#  name: projects/harshit-patel/global/networks/default
#  subnetwork_name: default
#  name: projects/harshit-patel-ae/global/networks/shared-vpc-network
#  subnetwork_name: shared-vpc-network
#  instance_tag: aef-inst
liveness_check:
  initial_delay_sec: '300'
  check_interval_sec: '30'
  timeout_sec: '4'
  failure_threshold: 4
  success_threshold: 2
readiness_check:
  check_interval_sec: '5'
  timeout_sec: '4'
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: '300'
