runtime: python39
entrypoint: gunicorn -b :$PORT blog.wsgi
env_variables:
  DB_HOST: 
  DB_NAME: 
  DB_PASSWORD: 
  DB_PORT: '3306'
  DB_TYPE: cloudsql
  DB_USER: 

vpc_access_connector:
  name: "projects/harshit-patel/locations/us-central1/connectors/new-vpc-connector"
  egress_setting: all-traffic